# .github/workflows/dotnet-build.yml

name: DepotDumperMorrenusEdition

on:
  push:
    branches: [ "main" ] # Or your default branch (e.g., master)
  pull_request:
    branches: [ "main" ] # Or your default branch (e.g., master)

jobs:
  build:
    runs-on: windows-latest # Use Windows runner due to potential platform dependencies

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up the specified .NET SDK version
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        # Ensure this version supports .NET 9.0 or use a specific SDK version if needed
        dotnet-version: '9.0.x' 

    # Restores dependencies for the project
    - name: Restore dependencies
      run: dotnet restore "DepotDumper/DepotDumper.csproj"
      # Use the relative path to your .csproj file from the root of the repository

    # Builds the project in Release configuration
    - name: Build project
      run: dotnet build "DepotDumper/DepotDumper.csproj" --configuration Release --no-restore
      # Use the relative path to your .csproj file

    # --- Optional Steps ---

    # If you add unit tests later, uncomment this section
    # - name: Run Tests
    #   run: dotnet test --no-build --verbosity normal # Add path to test project if needed

    # Example: Upload build artifacts (adjust path/pattern as needed)
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: depot-dumper-build
    #     path: DepotDumper/bin/Release/net9.0/ # Path to the output directory
